version: '3'

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    command: >
      sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:1.23.2-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/
      - ./.docker/nginx/log:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - nodejs
    networks:
      - app-network

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fullcycle
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local